HPP_FILES := $(shell find -L ../src/beginner_tutorials/ -name '*.h') $(shell find -L . -name '*.hpp')
CPP_FILES := $(shell find . -name 'dag*.cpp' -not -name 'plugin.cpp' -not -name 'main.cpp' -not -path '*/tests/*')
include common/common.mk
